### ISSUE TITLE
Support for the Amazon Fire phone

### ISSUE THREAD

**Issue by paulcwatts** [OneBusAway/onebusaway-android#158]
I have no idea what this entails, other than perhaps fixing #86 and getting approved in the Amazon App store.

**Comment by barbeau** [comment]
So I believe we have two main items we need to overcome to port to Fire Phone:
* Maps API (v1 for master branch, and v2 for develop branch)
* Google Play Services Location Services
  *  One-shot location requests (master and develop branches)
  *  Ongoing location updates (develop branch only - we needed to add this for showing real-time location on Maps API v2)

**Maps:**

Maps API v1 and v2 requires complete replacement of Google Map classes with Amazon equivalents, and I believe will need a new Gradle build flavor with replacement classes for this to be sustainable.

Amazon Maps API v1 guidance (for master branch):
https://developer.amazon.com/public/apis/experience/maps/doc/01-understanding-the-amazon-maps-api

Amazon Maps API v2 guidance (for develop branch):
https://developer.amazon.com/public/apis/experience/maps/docs-v2/migrating-an-app-from-google-maps-v2

One feature of Maps API v2 we're using is flat markers, and this isn't supported on Amazon - not sure how the current markers will appear without this:
https://developer.amazon.com/public/apis/experience/maps/docs-v2/differences-between-amazon-maps-api-v2-and-google-maps-api-v2

**Location services:**

I'm not currently sure of behavior here - here's my question to Amazon - I'll clarify this later once I figure it out:

>The main build-time issue I see that we need to overcome is that the LocationClient is initialized by each Activity/Fragment that uses it, and then injects the instantiated LocationClient into the LocationHelp class.  This is required to allow the LocationClient time to initialize before requesting a location, and to make sure location is only running while that UI component is visible (i.e., its torn down during onStop() of those components).  If I need to eliminate all references to LocationClient, this becomes problematic, since I'd need to duplicate all these Activities/Fragments in the other build flavor.

>Two quick questions, then:

>1.  Can I leave the build dependency on classes from Google Play Services such as LocationClient in the project?  In other words, can I still bundle the Play Services library?  Or do these need to be removed to compile/run on Fire Phone?
2.  If "Yes" to 1), what's the behavior when GooglePlayServicesUtil.isGooglePlayServicesAvailable() is called? If this just returns false, then we might be ok as-is for one-shot location requests.
I'd also need to check and see that where we're currently requesting on-going location updates that we're also using the original LocationManager, so we get updates if Play Services isn't available - I think this just applies to our develop branch though, where we've updated to Maps API v2.  I believe the only ongoing location updates in our master branch is part of Maps API v1, which was managed internally by this component.

**Comment by barbeau** [comment]
Amazon says:

>You would have to remove the dependency [on Google Play Services]. Because Amazon does not have a LocationClient object you’re project wouldn’t compile.

I don't think this is correct, though.  I believe Play Services stubs from the Play Services library (specified via the Gradle dependency) are bundled with the project, hence the availability of the `GooglePlayServicesUtil.isGooglePlayServicesAvailable()` method, which I assumes tries to do IPC with Play Services, and returns false if this fails.  A quick run of the current develop branch on the Fire Phone seems to confirm this, since the project crashes on a NPE when trying to get the Google Map API v2 GoogleMap reference, but otherwise builds and executes,and prints `W/GooglePlayServicesUtil﹕ Google Play services is missing` in LogCat.

**Comment by barbeau** [comment]
New problem - for some reason the Amazon Maps API v2 AAR library file is not available via Jcenter or Maven Central.

My question to Amazon:

>why isn't the AAR library for Amazon Maps API v2 available via Maven Central or Jcenter?

>As specified here, for a developer to be able to compile the project using Android Studio/Gradle, it requires manual setup to install the AAR file in your local Maven repo:
https://developer.amazon.com/public/apis/experience/maps/docs-v2/configuring-your-project-to-use-the-amazon-maps-api-v2#Referencing the Amazon Maps API Support Library

>The critical issue here is that we use Travis as our CI build server - this requires a completely scripted build process, which doesn't currently seem possible if manual download/install steps are necessary.  We've also worked hard to eliminate manual environment setup to make things simpler for developers who want to contribute to the open-source project.

>Uploading the Amazon Maps API v2 AAR file to Jcenter or Maven Central seems like a simple solution that could easily be accomplished on Amazon's end.

There is a workaround where we could manually bundle the AAR file in the libs directory, but I'd really rather avoid that.  I'm guessing the lack of availability via Maven Central or Jcenter is due to ToS agreement, we'll see.

**Comment by barbeau** [comment]
Well, the [previous workaround](https://github.com/CUTR-at-USF/usf-step-sensor-demo/blob/master/app/build.gradle) I've used to manually bundle the AAR file in the libs directory doesn't seem to work for some reason, and neither does the ["Import AAR"](http://stackoverflow.com/a/24894387/937715) option in Android Studio.  Will have to investigate further...

**Comment by yaroslavd** [comment]
Hi guys! Any good news on progress? Can't wait to see OBA on the Amazon App Store!

**Comment by barbeau** [comment]
@yaroslavd Thanks for checking in!  I haven't had a whole lot of time to work on this, but we're getting there gradually.  The largest obstacle is making sure we can properly support both a Google Play and Amazon App Store version going forward.

**Comment by barbeau** [comment]
I've started work on Amazon Maps API v2 version here:
https://github.com/OneBusAway/onebusaway-android/tree/amazonMapsV2

It currently builds, but will crash when trying to load the map (since its still referencing the Google Map API v2 classes).

Note that to build this requires the manual installation of the Amazon Maps API v2 AAR file to your local Maven repo, as instructed in:
https://developer.amazon.com/public/apis/experience/maps/docs-v2/configuring-your-project-to-use-the-amazon-maps-api-v2#Referencing the Amazon Maps API Support Library

**Comment by barbeau** [comment]
I just bundled the AAR in this project (required for building on Travis), so you can install in your local Maven repo by running:
`mvn install:install-file -Dfile=libs/amazon-maps-api-v2.aar -DpomFile=amazon-maps-api-v2.aar.pom`

**Comment by barbeau** [comment]
Another obstacle - per https://github.com/OneBusAway/onebusaway-android/issues/105, we will soon have Google Analytics integrated into OBA Android.

And, per the following link, this isn't available on Amazon devices either:
http://forums.developer.amazon.com/forums/message.jspa?messageID=11294

**Comment by barbeau** [comment]
Well, maybe analytics isn't an obstacle - response from Amazon:

>You can use Google Analytics on Amazon devices.
 
>Note: Google Analytics can be used and will work on devices that do not have Google Play Services. In this case you still download and use the Google Play Services SDK and Google Analytics will automatically fall back to local dispatching.
https://developers.google.com/analytics/devguides/collection/android/v4/
 
>Alternatively, you can switch to Amazon Mobile Analytics, which supports iOS, Android, and FireOS ;)
>http://aws.amazon.com/mobileanalytics/

Reading the Google Analytics docs, it seems like this should magically work.

**Comment by yaroslavd** [comment]
You'd want to be careful about failing gracefully. I sideload Snapchat on
my Fire Phone, and it works, but I do get the message on startup that it
requires Google Services (that I can safely dismiss, and keep using the
app).

**Comment by barbeau** [comment]
@yaroslavd Ok, thanks, good to know.  So you get the notice about Google Services every time you start Snapchat?

**Comment by yaroslavd** [comment]
Yes, and intermittently after startup (probably when they try to send the
batch). It doesn't say which Google Service it needs, but I can't think of
anything else it'd be other than Analytics. I'd imagine you can check for
presence of Google Analytics before making the call, although I'm guessing.

**Comment by bbodenmiller** [comment]
I don't think it is Google Analytics making this error message as the docs say it can be used without Play Services. I imagine it is likely a result of using Play Services Location APIs.

**Comment by barbeau** [comment]
Looked at this port a bit more this evening, including building with different Gradle build flavors.

One thing I haven't been able to get around is the following build errors, which appear using the amazonMapsV2branch:
~~~
Error:(50, 21) No resource found that matches the given name: attr 'android:actionModeShareDrawable'.
~~~

...and a bunch more related to the Material style from the support library.  This seems to be the issue:
http://stackoverflow.com/questions/26431676/appcompat-v721-0-0-no-resource-found-that-matches-the-given-name-attr-andro

Unfortunately, our compileSdkVersion can't be 21, since it needs to be:
`compileSdkVersion "Amazon.com:Amazon Fire Phone SDK Addon:17"`

And, you currently can't change compileSdkVersion as part of build flavors:
https://code.google.com/p/android/issues/detail?id=64985

What's strange is that the current amazonMapsV2 branch built at some point on my work machine, but now I can't get it to build.  Not sure if updates to the Android SDK broke something.  Will need to look into it more.

**Comment by barbeau** [comment]
Per Amazon, apparently Fire Phone SDK is only required as `compileSdkVersion` if you use Fire Phone-specific APIs.  So, we can use `compileSdkVersion 21`, which fixes the above issue.

**Comment by barbeau** [comment]
amazonMapsV2 branch is now properly configured with Gradle build flavors to build either Amazon or Google versions of the app (see "Build variants" window in Android Studio).

I also registered the debug keystore with Amazon, so the app now runs on the Fire Phone and I can see the map (an aside - apparently no API key is necessary, registering the applicationId and debug keystore with Amazon is enough).

However, seems like there are still a few items to sort out:

1.  LatSpan/LonSpan and center of the map isn't calculated correctly - I'm seeing  `http://api.tampa.onebusaway.org/api/api/where/stops-for-location.json?lat=0.0&lon=0.0&latSpan=NaN&lonSpan=NaN` in DDMS.  As a result, no stops appear on the map.  Need to dig into this further.
2.  Floating Action Button for MyLocation covers the zoom in/zoom out buttons - We disable these controls on Google Maps, but it doesn't look like the disabling works on Amazon Maps API v2.

**Comment by barbeau** [comment]
Ah - I think 1) above is a side effect of 4).

**Comment by barbeau** [comment]
Fixed 1) and 4), and got the Maps V2 / bus stop loading stuff to work:

![amazonmapsapiv2-small](https://cloud.githubusercontent.com/assets/928045/6071135/a0ff83ba-ad60-11e4-973f-a36b5cb7dd3f.png)

However, for some reason real-time location doesn't seem to be working.  So, here's remaining issues I've noticed so far:

1.  **Floating Action Button for MyLocation covers the zoom in/zoom out buttons** - We disable these controls on Google Maps, but it look like the disabling doesn't work on Amazon Maps API v2.
2.  **No back button in Settings** - There isn't a hard back button on the Fire Phone, so you currently get locked into the Settings screen when entering it. This should be fixed by adding the ActionBar back to the PreferencesActivity.
3.  **Real-time location doesn't work** - Getting real-time location doesn't seem to work.  From DDMS I can see its fetching location from Location API v1, but I need to look into this further.

If anyone looking at this wants to try the current APK on their Fire Phone, you can download it [here](https://dl.dropboxusercontent.com/u/46443835/OneBusAway/Amazon%20Fire%20Phone/onebusaway-android-amazon-debug.apk).  I imagine you'll need to turn on the equivalent feature to Google's "Allow apps that aren't from Google Play".

**Comment by barbeau** [comment]
So for 3) real-time location I forgot that the location update mechanism was different for Maps API v2 real-time position, and right now that's being driven only by Fused Location Provider, which isn't available on Amazon devices, which is why we're not seeing any updates.  The solution is to add monitoring for both Location API v1 and Fused Provider in BaseMapFragment, which should help for any platform that doesn't have Play Services installed.

**Comment by barbeau** [comment]
And, I believe 1) zoom controls covering FAB fixed itself when I fixed the "install Google Maps" message/setup.

So, given that 2) and 3) are technically not Amazon-specific issues, we should be ready to merge this into develop.  I'll work on squashing the commits and pushing into the PR.

**Comment by barbeau** [comment]
Fixed for develop branch in https://github.com/OneBusAway/onebusaway-android/pull/208.  Now I need to figure out if its worth back-porting to master, or if we just target the first Amazon release when the develop branch reaches release.

**Comment by bbodenmiller** [comment]
How much work is left on the develop branch? Is GA also dependent on develop branch being fixed up?

**Comment by barbeau** [comment]
Not a whole lot - major items that still need to be added for initial release are a slight redesign of sliding panel header, ability to see routes list and interact with routes view after tapping on stop, and recent stops/routes by tapping on search box.  And some general cleanup, listed at top of #177.

For GA, @cagryInside already submitted a PR that I need to finish reviewing for GA in the master branch.  He's working on another PR for the develop branch.

**Comment by barbeau** [comment]
I'm going to go ahead and close this issue (fixed in 0d8d7e2aa9e6fddabd74624564183b3077b2b592) and plan to do the first release on Amazon App Store with new UI.

If you have a Fire Phone and want to try an early version of the new UI, I'll keep a stable APK that you can side-load here:
https://dl.dropboxusercontent.com/u/46443835/OneBusAway/Amazon%20Fire%20Phone/onebusaway-android-amazon-debug.apk

Note that you'll need to enable app installations from sources other than the Amazon Appstore to install this APK on your Fire Phone.  Instructions for doing this, as well as sideloading the APK, are available in [this CNET article](http://www.cnet.com/how-to/how-to-sideload-apps-on-the-amazon-fire-phone/).

**Comment by yaroslavd** [comment]
I've been sideloading this on my Fire Phone without issues for some time now (thanks for the quick turnaround!).

However, I still don't see this in the Amazon App Store. Is that being tracked in another issue?

**Comment by bbodenmiller** [comment]
@yaroslavd my understanding is that @barbeau plans to release to the Amazon App Store once https://github.com/OneBusAway/onebusaway-android/issues/155 (WIP at https://github.com/OneBusAway/onebusaway-android/pull/177) is complete.

**Comment by barbeau** [comment]
@yaroslavd Thanks for letting us know it seems to be working well on Fire Phone!  My original plan was to finish the UI redesign (#155) and then launch identical versions simultaneously for Google Play and Amazon App Store.  However, for several reasons its taking longer to wrap up the UI design than I originally planned (long stories).  I've been getting prodded by several Fire Phone users about doing a release on Amazon App Store as-is, since even the current implementation is a significant improvement over the mobile web app, which is the other baseline option on Fire Phone.  I'm seriously considering this - ideally I'd still like to squash a few bugs that I know exist (see top of #177) before I do an official Fire Phone general public release.  Another option is to load up the sideloaded APK into the Amazon [Live App Testing](https://developer.amazon.com/appsandservices/resources/development-tools/live-app-testing) so more users can download directly from Amazon App Store vs. sideloading.

@yaroslavd What are your thoughts?  Know other Fire Phone users that would be interested in signing up for a live app test?

**Comment by yaroslavd** [comment]
Thanks Sean! I would strongly encourage you to publish as-is. It's mounds better than the web app, and is very stable. Frankly, I like it better than the iPhone app (granted, last time I've used that was almost a year ago). I would definitely look forward to improvements in the linked issues, but from my experience the app works great, as-is.

**Comment by barbeau** [comment]
Sorry!  Just realized I never posted the final URL for production Fire Phone release here.  You can download OneBusAway Fire Phone from [Amazon App Store](http://www.amazon.com/gp/mas/dl/android?p=com.joulespersecond.seattlebusbot)!
