### ISSUE TITLE
Jumping markers on Maps v2

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#289]
*For `develop` branch*

I'm seeing markers jump around on the map on Android Maps API v2 even when nothing is happening in the app.  

Here's a video of the behavior:

https://youtu.be/cOUGD0T5Ojs

*What I expect* 

Markers should remain stationary at their originally added lat/long.

*What steps will reproduce the problem?* 

* 1a. Download the APK from:
https://dl.dropboxusercontent.com/u/46443835/OneBusAway/UI_redesign/onebusaway-android-oba-google-debug.apk

or

* 1b. Build, install, and run the develop branch of OneBusAway:
 * a. `git clone https://github.com/OneBusAway/onebusaway-android.git`
 * b. `git checkout develop`
 * c. `gradlew installObaGoogleDebug`
 * d. `adb shell am start -n com.joulespersecond.seattlebusbot/org.onebusaway.android.ui.HomeActivity`

* 2. Browse to any supported city (e.g., Seattle or Tampa), and watch the green bus stop markers jump around on the map

I should add that I can't *always* reproduce this.  It seems like everything works fine for a time, but then when the markers start jumping around they don't stop.

*Marker Implementation Details*

The code that loads the icons used for the 9 marker types (8 directions + no direction) is here:
https://github.com/OneBusAway/onebusaway-android/blob/develop/onebusaway-android/src/google/java/org/onebusaway/android/map/googlemapsv2/StopOverlay.java#L169

I'm using this drawable:
https://github.com/OneBusAway/onebusaway-android/blob/develop/onebusaway-android/src/main/res/drawable/map_stop_icon.xml

...which is a number of shapes - this creates the main green circle with the white outline and the drop shadoes.  Then, I'm drawing the direction arrow on top of this drawable for each of the 8 directions - code for drawing directions is here:

https://github.com/OneBusAway/onebusaway-android/blob/develop/onebusaway-android/src/google/java/org/onebusaway/android/map/googlemapsv2/StopOverlay.java#L202

In the code to load the icons, I'm caching the `BitmapDescriptor` returned from `BitmapDescriptorFactory.fromBitmap()` for each of the 9 icon types on first load, so this isn't done each time a marker is put on the map.

I also saw the app crash to "Unfortunately, OneBusAway has stopped." and saw this exception in Logcat after letting the app sit on the map screen for a few minutes:

    08-10 16:40:02.422  15843-15929/com.joulespersecond.seattlebusbot E/AndroidRuntime﹕ FATAL EXCEPTION: GLThread 8614
        Process: com.joulespersecond.seattlebusbot, PID: 15843
        java.lang.IllegalArgumentException: Comparison method violates its general contract!
                at java.util.ComparableTimSort.mergeHi(ComparableTimSort.java:831)
                at java.util.ComparableTimSort.mergeAt(ComparableTimSort.java:449)
                at java.util.ComparableTimSort.mergeCollapse(ComparableTimSort.java:372)
                at java.util.ComparableTimSort.sort(ComparableTimSort.java:178)
                at java.util.ComparableTimSort.sort(ComparableTimSort.java:142)
                at java.util.Arrays.sort(Arrays.java:1957)
                at java.util.Collections.sort(Collections.java:1864)
                at com.google.maps.api.android.lib6.gmm6.n.bl.a(Unknown Source)
                at com.google.maps.api.android.lib6.gmm6.n.l.a(Unknown Source)
                at com.google.maps.api.android.lib6.gmm6.n.l.b(Unknown Source)
                at com.google.maps.api.android.lib6.gmm6.n.cv.f(Unknown Source)
                at com.google.maps.api.android.lib6.gmm6.n.cv.run(Unknown Source)

I've seen this on an LG G4 and Nexus 6.  More details on LG device is below.

* LG G4 LS991 with Android 5.1 (LS991ZV4)

* Google Play Services client library version = `compile 'com.google.android.gms:play-services-maps:7.5.0'` and `compile 'com.google.android.gms:play-services-maps:7.8.0'`

* Google Play Services version on the device - Google Play Services 7.8.99 (2134222-440)

* Android SDK Version: `compileSdkVersion 21 buildToolsVersion "21.1.2"`

This issue hasn't always existed, which makes me believe it was introduced during an update to Android Google Play Services/Maps at some point.

I've opened an issue for this on gmaps-api-issues as well, but no response as of this post:

https://code.google.com/p/gmaps-api-issues/issues/detail?id=8455

I've created a smaller demo project here on Github that uses the same marker implementation:

https://github.com/barbeau/maps-demo

...but so far I haven't been able to reproduce the problem there.

**Comment by barbeau** [comment]
I've also posted to StackOverflow on this problem:
http://stackoverflow.com/questions/32276570/jumping-markers-on-android-maps-api-v2

There have been a few upvotes so far, so I guess we're not the only ones seeing this.

**Comment by barbeau** [comment]
And a post to the Google+ Android Developers community:
https://plus.google.com/u/0/+SeanBarbeau/posts/RrSYWxy7NUt

**Comment by barbeau** [comment]
I just pushed https://github.com/OneBusAway/onebusaway-android/commit/01b35e9a07313a627843819d66b3f6a9bb7e848f to the `develop` branch, which changes to caching `Bitmaps` instead of `BitmapDescriptors` for map icons.  If Maps API v2 implementation is doing some kind of recycling of `BitmapDescriptors` this could potentially fix the problem.

@cagryInside could you start running this on your Nexus 6 and let me know if you see the problem again?

I can't always reproduce this on my LG G4, as its intermittent.  So, I can't really saw whether or not this commit conclusively fixed the problem yet, unless neither of us see the issue again after a period of time.

**Comment by barbeau** [comment]
I'm still seeing the problem, so looks like switching from caching `BitmapDescriptors` to `Bitmaps`, and changing to using `ContextCompat.getDrawable()`,  didn't have any effect.

**Comment by cagryInside** [comment]
@barbeau Just checked with my nexus 6, I don't see the problem. But, I rolled back the latest development, I still don't see the problem. So, I don't think it did any effect.

**Comment by barbeau** [comment]
Yeah, this one has been tricky to reproduce.  After doing a new debug install it doesn't always happen right away.  Seems like after a while something breaks in the Maps API implementation, and after this happens then the jumping markers persist for a while.  It also seems to happen per-app - last night I saw the issue in OBA, and switched to the [maps-demo project](https://github.com/barbeau/maps-demo) I created, but didn't see the issue in that app.

**Comment by barbeau** [comment]
I haven't seen this issue lately, and I noticed that Google Play services on my device was bumped to 8.1.15.  So, maybe it was fixed with an update of Google Play services?

@cagryInside (or anyone else) - if you see this problem again, please let me know, and let me know which version of Google Play services your device has.

**Comment by barbeau** [comment]
Talking to @cagryInside today, he hasn't seen this on his Nexus 6 recently either - currently running Play Services 8.1.15.  I'm going to close this for now, and will re-open if we see the problem again.

**Comment by barbeau** [comment]
Just saw this again - I think it may be triggered by stacking multiple Activities that use the map on top of each other, and then closing them by hiting the back button.

There is a new version of Play Services available in the build tools, we should try this.

**Comment by barbeau** [comment]
I'm still seeing this after bumping Play Services to 8.1.0 in build.gradle.  It's more subtle than its been in the past - sometimes the shift of the markers is just changes in the Z-order, with the position unchanged.  But, jumping of markers to places where there shouldn't be markers can still be seen.

**Comment by barbeau** [comment]
For the current `develop` branch, if you tap on an arrival time select the option to "Show route on map", let the map with vehicle positions load, and then change the orientation of the screen to landscape, this seems to trigger the behavior every time I've tried it, and really bad - they jump all over the screen.  Here's a video screen capture:
https://youtu.be/gYBunJYZTMo

Strangely, if you return back to portrait orientation, the jumping stops, and everything goes back to normal.

This is still using Play Services to `8.1.0` in `build.gradle`, and Play Services `8.3.00 (2353383-240)` on an LG G4 w/ Android 5.1.

**Comment by barbeau** [comment]
Interestingly, if you start with the arrival screen in landscape mode, and then tap on "Show route on map" so this map screen loads in landscape, the markers don't jump around.  And, if you switch to portrait while on that screen, the markers also don't jump around.  But, if you change the orientation back to landscape, then the markers start jumping.  So the orientation change from portrait to landscape while viewing the route mode on map seems to trigger the jumping.

**Comment by barbeau** [comment]
Play Services 8.3 was released today, so just bumped Play Services to `8.3.0` in `build.gradle` in https://github.com/OneBusAway/onebusaway-android/commit/77804b8aa67291ecbb3ab9a74ef73f228ce4d222.  No effect on this issue - when switching route mode to landscape orientation I still see the markers jump around the screen.

**Comment by barbeau** [comment]
AFAIK there isn't anything we can do to prevent this issue - it just happens.  So, I'm going to leave it open but push it to a future milestone.  Under normal use/conditions it doesn't seem bad/frequent enough to block a public v2.0 release.  But, we should continue to track it.

**Comment by barbeau** [comment]
Whoops, this was automatically close by Github in the merge to master.

**Comment by barbeau** [comment]
This issue may have been fixed by https://github.com/OneBusAway/onebusaway-android/commit/1fe8756c7413d3479af21d440cbf8b848c5ae2fa, which fixed a leak of the `BaseMapFragment` (which extends the `SupportMapFragment`).

From my SO post (http://stackoverflow.com/a/34227146/937715):

>I think this is definitely related to multiple instances of the `SupportMapFragment` existing simultaneously.  In `v2.0.6` I wasn't handling fragments correctly when the Activity was destroyed and recreated with a savedInstanceState (i.e., when the Activity was killed after being in background for a while, or on orientation change).

>In `v2.0.6`, my code looked something like this:

    public class HomeActivity ...{

        BaseMapFragment mMapFragment;

        ...

        private void showMap() {
            FragmentManager fm = getSupportFragmentManager();
            if (mMapFragment == null) {
                    mMapFragment = BaseMapFragment.newInstance();
                    fm.beginTransaction()
                        .add(R.id.main_fragment_container, mMapFragment)
                        .commit();
            }
        }
        ...
    }

>So, I was leaking an instance of `BaseMapFragment` (which extends `SupportMapFragment`) in those cases - an instance already existed in the `FragmentManager`, but I didn't have a local reference to it.  I actually noticed this issue when Action Bar menu items were being duplicated for another fragment I was handling similarly.

>I changed the code to look something like this, which first checks to see if the `FragmentManager` has an existing `BaseMapFragment`:

    public class HomeActivity ...{

        BaseMapFragment mMapFragment;

        ...

        private void showMap() {
            FragmentManager fm = getSupportFragmentManager();            
            // First check to see if an instance of BaseMapFragment already exists            
            mMapFragment = (BaseMapFragment) fm.findFragmentByTag(BaseMapFragment.TAG);

            if (mMapFragment == null) {
                mMapFragment = BaseMapFragment.newInstance();
                fm.beginTransaction()
                        .add(R.id.main_fragment_container, mMapFragment, BaseMapFragment.TAG)
                        .commit();
            }
        }
        ...
    }

>The UI flow has changed in the master branch (I'm no longer opening a new Activity to view the route), so I can't directly test there if the problem is still reproducible after this code change.

>*However*, I created this branch, which is branched from master but changed to have the same UI flow as v2.0.6, and includes the above fix for the fragment leak:

https://github.com/CUTR-at-USF/onebusaway-android/tree/jumpingMarkersTest

>From some quick testing with this branch, it seems that handling the fragments correctly on orientation change (i.e., not leaking the fragment) *may* have fixed the jumping markers issue - at least using the steps above it no longer reproduces on a LG G4 with Android 5.1.

I'm going to close this for now, and will re-open if I see it again.
