### ISSUE TITLE
Cut back on tutorial frequency/amount

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#526]
Only negative feedback I've heard from a user so far with the 2.0.12 public rollout (we're currently at 5%):

>wayyyyyy too many "Got it?!" pop-up notifications in the new app. I get that it's new, it's trying to help me figure out how to use it... but I just want to use the dang app! And when I get 10 (almost literally) pop-ups preventing me from just using it, whenever I hit ANYTHING in the new app, it is SUPER annoying. Pare them back!!

We can either space out the tutorials a bit more, or perhaps cut back on some that are more obvious.

**Comment by azizmb9494** [comment]
+1 one on cutting back. I had similar thoughts when first using the app. If it helps, when I get my Android back, I'll go through tutorial & suggest those I think are obvious.

**Comment by barbeau** [comment]
Thank @azizmb9494!

If anyone else has suggestions on which to cut I'd like to hear it.  I think I'll probably take an initial cut at this tomorrow and release as a hotfix along with some of the Spanish translation updates.

**Comment by barbeau** [comment]
Something else that can help here - we can space out the tutorials more (with a counter and mod(3)), and if the user taps on the functionality covered by a tutorial they haven't seen yet, we can just never show that tutorial.  If they've found it themselves we don't need to show them a tutorial about it.

**Comment by barbeau** [comment]
More user feedback on this topic:

>* Can you please provide an option to disable the tutorial.  I do not need the tutorial every single time I open the app.

>* Way way way way too many instructional pop-ups.  Way too many.  Did I mention how many there were?  There were too many. By far.

**Comment by barbeau** [comment]
@azizmb9494 and @cagryInside Could you please take a look at this branch which cuts back on the tutorials, and see what you think?

https://github.com/OneBusAway/onebusaway-android/tree/cutBackTutorials

From commit summary:

>* Eliminates a number of lesser important tutorials for minor features
* Uses a global counter to space out notification internal and avoid spamming users with tutorials back-to-back for different features
* If a user discovers a feature on their own before seeing a tutorial for that feature, then don't show them that tutorial (a few exceptions here for features like starring routes, for which the outcome may not be obvious to the user)

**Comment by barbeau** [comment]
@cagryInside I just pushed https://github.com/OneBusAway/onebusaway-android/commit/4f19c74c6608f23444f596fb6994d41e60b9aec8 to the same branch, which I believe should fix the problem of the "Starred route" tutorial focusing on the wrong part of the screen due to the sliding panel being in motion.  Please let me know if you see that problem again when running with this commit.

**Comment by azizmb9494** [comment]
@barbeau: Looks like a good direction to me (doing both the cutback & spacing out), still can't play with it since Android still isn't here :/ (Shipped a bunch of my stuff by mail when moving across the country).

**Comment by barbeau** [comment]
@azizmb9494 Sure, thanks, no problem.  FYI, you might want to try out the emulator with the new version of Android Studio - much better than its been in the past.

**Comment by barbeau** [comment]
Users definitely feel passionately about this - more user feedback:

>Too many popups! No way to turn it off. If I see that green popups that says Got it! Instead of the information I need and no way to discontinue them permanently I am going to keep writing until they're gone gone gone!!!!

I've halted the existing rollout and will likely cut a new release tomorrow to get an update out to fix this.  So if anyone has further suggestions on improvements please speak up now before this goes out.

**Comment by bbodenmiller** [comment]
Its been awhile since I've viewed the tutorial (is there a way to reset it?) but does it get in the way of users performing actions and require them to click Got It before proceeding? If so, it might be better if it was suggestions that didn't require a user action to dismiss.

**Comment by barbeau** [comment]
You can reset tutorial via "Help->Show Tutorial."

Yes, the ShowcaseView library requires tapping on button to dismiss
screen.  I'll look and see if there are options to dismiss via other
actions.
On Jun 9, 2016 1:28 AM, "Ben Bodenmiller" <notifications@github.com> wrote:

Its been awhile since I've viewed the tutorial (is there a way to reset
it?) but does it get in the way of users performing actions and require
them to click Got It before proceeding? If so, it might be better if it was
suggestions that didn't require a user action to dismiss.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/OneBusAway/onebusaway-android/issues/526#issuecomment-224803384>,
or mute the thread
<https://github.com/notifications/unsubscribe/AA4pLfy1Tj4J9RTgKnA6w5xhSJzfry1pks5qJ6RsgaJpZM4Iuf_y>
.

**Comment by themonki** [comment]
@barbeau How about deactivate the tutorial and showing a first pop-up saying:

You want to see the tutorial on how to use OneBusAway?

Options Yes or No

And then call the tutorial.

**Comment by barbeau** [comment]
@themonki Good idea - that's exactly what we were talking about here.  Similar option would be to include checkbox within the tutorial screen to "show these screens".  There are some implementation and UX challenges here to turn this out quickly, so we're taking a look now.

**Comment by barbeau** [comment]
Alright, just force-pushed a new commit to the same https://github.com/OneBusAway/onebusaway-android/tree/cutBackTutorials branch that combines all the related commits, and adds a preference to turn on/off tutorial popups at any time.  Also, following the "What's new?" dialog, the user is now prompted asking if they want to see the tutorial:

![image](https://cloud.githubusercontent.com/assets/928045/15940116/8e8c5c8e-2e48-11e6-93f5-4faa1ea718e7.png)

**Comment by barbeau** [comment]
@themonki Would you be able to do a quick Spanish translation for the new strings in https://github.com/OneBusAway/onebusaway-android/commit/6a44a8c38dc6ab84225ab0eb83ae0d497a530c9b?

Should only be 3-4 strings, for the preference and above dialog.

**Comment by themonki** [comment]
Ok, I am working on this.

**Comment by themonki** [comment]
@barbeau done on PR #534
